---
- hosts: all
  become: yes
  tasks:
  
  - name: "Check user"
    shell: cat /etc/passwd
    register: check_user
    ignore_errors: yes
  - debug:
      var: check_user

  - debug:
      msg: "User EXIST"
    when: ('ayam' in check_user.stdout)
  - debug:
      msg: "User DOESN'T exist"
    when: ('ayam' not in check_user.stdout)

  - name: "Change user password"
    user:
      name: ayam
      update_password: always
      password: "{{ newpassword|password_hash('sha512') }}"
    register: update_passwd
    when: ('ayam' in check_user.stdout)
  - debug:
      var: update_passwd
    
