---
- hosts: all
  become: yes
  tasks:

  - name: "Update user password"
    user:
      name: ayam
      update_password: always
      password: "{{ newpassword|password_hash('sha512') }}"
    register: update_passwd
  - debug:
      var: update_passwd
    
